### ISSUE TITLE
App not running locally on my machine

### ISSUE THREAD

**Issue by ghost** [blk-labs/mph-news#7]
I am having issue running the app locally after cloning it from the repo, the dependencies has been installed.
![Screenshot from 2022-04-25 13-22-33](https://user-images.githubusercontent.com/104018388/165089122-c1a18277-9e51-4214-b95d-f528a886b14d.png)

The error message states that: `Failed prop type: The prop `width` is marked as required in `App`, but its value is `undefined`

**Comment by maker-jr** [comment]
That looks like a harmless warning. Can you provide more information? What does the browser show when you try to visit the url?

**Comment by maker-jr** [comment]
I just cloned the repo, its working on my end. Are you still having this problem?

**Comment by kayodelab** [comment]
Done, I used yarn to set it up initial, I guess that was why I experienced that. It is working fine niw.
